name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest

    outputs:
      libffi-version: ${{ steps.fetch.outputs.libffi-version }}

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
    - name: Get build information from build.toml
      id: fetch
      run: |
        echo "libffi-version=$(cat ./libffi-version)" >> $GITHUB_OUTPUT
    - name: Download libffi source
      working-directory: source
      run: >
        gh release -R libffi/libffi
        download v${{ steps.fetch.outputs.libffi-version }}
        -p libffi-${{ steps.fetch.outputs.libffi-version }}.tar.gz
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Extract tarball
      working-directory: source
      run: tar -xzf libffi-${{ steps.fetch.outputs.libffi-version }}.tar.gz
    - name: Upload libffi source artifact
      uses: actions/upload-artifact@v4
      with:
        name: libffi-${{ steps.fetch.outputs.libffi-version }}
        path: ${{ github.workspace }}/source/libffi-${{ steps.fetch.outputs.libffi-version }}
        if-no-files-found: error
        retention-days: 1

  build:
    name: Build (${{ matrix.build.target }})
    needs: fetch
    runs-on: ${{ matrix.build.runner }}
    strategy:
      fail-fast: false
      matrix:
        build:
        - runner: ubuntu-latest
          target: x86_64-unknown-linux-gnu

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
    - name: Download libffi source artifact
      uses: actions/download-artifact@v4
      with:
        name: libffi-${{ needs.fetch.outputs.libffi-version }}
        path: ${{ github.workspace }}/source/libffi
    - name: Configure
      working-directory: source/libffi
      run: >
        ./configure
        --prefix=${{ github.workspace }}/libffi
        --host=${{ matrix.build.target }}
        CC=clang
        CFLAGS="--target=${{ matrix.build.target }}"
        CXX=clang
        CXXFLAGS="--target=${{ matrix.build.target }}"
    - name: Build
      working-directory: source/libffi
      run: make -j$(nproc) install
    - name: Upload libffi artifact
      uses: actions/upload-artifact@v4
      with:
        name: libffi-${{ matrix.build.target }}
        path: ${{ github.workspace }}/libffi
        if-no-files-found: error
        retention-days: 1

  build-apple:
    name: Build (${{ matrix.build.target }})
    needs: fetch
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build:
        - target: aarch64-apple-ios10.0
          sdk: iphoneos
        - target: armv7s-apple-ios10.0
          sdk: iphoneos
        - target: aarch64-apple-ios10.0-simulator
          sdk: iphonesimulator
        - target: x86_64-apple-ios10.0-simulator
          sdk: iphonesimulator
        - target: aarch64-apple-darwin10.0
          sdk: macosx
        - target: x86_64-apple-darwin10.0
          sdk: macosx
        - target: aarch64-apple-tvos9.0
          sdk: appletvos
        - target: aarch64-apple-tvos9.0-simulator
          sdk: appletvsimulator
        - target: x86_64-apple-tvos9.0-simulator
          sdk: appletvsimulator
        - target: aarch64-apple-watchos2.0
          sdk: watchos
        - target: arm64_32-apple-watchos2.0
          sdk: watchos
        - target: armv7k-apple-watchos2.0
          sdk: watchos
        - target: aarch64-apple-watchos2.0-simulator
          sdk: watchsimulator
        - target: x86_64-apple-watchos2.0-simulator
          sdk: watchsimulator

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
    - name: Download libffi
      working-directory: source
      run: >
        gh release -R libffi/libffi
        download v${{ needs.fetch.outputs.libffi-version }}
        -p libffi-${{ needs.fetch.outputs.libffi-version }}.tar.gz
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Extract tarball
      working-directory: source
      run: tar -xzf libffi-${{ needs.fetch.outputs.libffi-version }}.tar.gz
    - name: Configure
      working-directory: source/libffi-${{ needs.fetch.outputs.libffi-version }}
      run: >
        ./configure
        --prefix=${{ github.workspace }}/libffi
        --host=${{ matrix.build.target }}
        CC=clang
        CFLAGS="--target=${{ matrix.build.target }} --sysroot=$(xcrun --sdk ${{ matrix.build.sdk }} --show-sdk-path)"
        CXX=clang
        CXXFLAGS="--target=${{ matrix.build.target }} --sysroot=$(xcrun --sdk ${{ matrix.build.sdk }} --show-sdk-path)"
        LDFLAGS="--target=${{ matrix.build.target }} --sysroot=$(xcrun --sdk ${{ matrix.build.sdk }} --show-sdk-path)"
    - name: Build
      working-directory: source/libffi-${{ needs.fetch.outputs.libffi-version }}
      run: make -j$(nproc) install
    - name: Upload libffi artifact
      uses: actions/upload-artifact@v4
      with:
        name: libffi-${{ matrix.build.target }}
        path: ${{ github.workspace }}/libffi
        if-no-files-found: error
        retention-days: 1
